name: Deploy Laravel App

on:
  push:
    branches:
      - main   # or master (your deployment branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Match your server PHP version
          extensions: mbstring, bcmath, intl, pdo_mysql
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run Laravel Tests
        run: php artisan test

      # Deploy to your server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/varnarcc/api_varnarc
            git reset --hard
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear
            php artisan config:cache
